fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/Cycatz/pre-commit-hooks
    rev: 2c81b7028344c94b90c3e0a54e41c3f07bda7393
    hooks:
      - id: clang-format
        args: [--style=file, .clang-format]
      - id: clang-tidy
        args: [--config-file=.clang-tidy]
      - id: cppcheck
      # - id: cpplint
      # - id: include-what-you-use
